Ensure default state in test is restored
Otherwise tests sometimes fail like so:
```
TestGemInstall#test_user_bundler:
LoadError: 126: The specified module could not be found.   - c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/ffi-1.17.3/lib/ffi_c.so
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/ffi-1.17.3/lib/ffi.rb:5:in 'Kernel#require'
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/ffi-1.17.3/lib/ffi.rb:5:in '<top (required)>'
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/win32-process-0.10.0/lib/win32/process/functions.rb:6:in 'Kernel#require'
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/win32-process-0.10.0/lib/win32/process/functions.rb:6:in '<top (required)>'
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/win32-process-0.10.0/lib/win32/process.rb:1:in 'Kernel#require_relative'
    c:/ri2-ruby/lib/ruby/gems/4.1.0+0/gems/win32-process-0.10.0/lib/win32/process.rb:1:in '<top (required)>'
    test/test_gem_install.rb:69:in 'Kernel#require'
    test/test_gem_install.rb:69:in 'TestGemInstall#with_test_user'
    test/test_gem_install.rb:122:in 'TestGemInstall#test_user_bundler'
```